In [1]:
import numpy as np
import scipy.stats as ss

## OLS REGRESSION

In [10]:
T = 750 #Choose a sample size
mu = (0,0,0) #Generate sample for Y and X
cov = [[1,0,0],[0,1,0],[0,0,1]]

F = np.random.multivariate_normal(mu,cov,T)
X = np.column_stack((np.ones((T,1)),F))
N = X.shape


beta = np.array([0.56,2.05,1,78])
beta.shape = (N[1],1)

#GEnerate sampel fo Y
Y = np.matmul(X,beta) + np.random.normal(0,1,(T,1))

In [19]:
F

array([[ 0.9756764 ,  1.27036092, -1.14654022],
       [-0.71516987, -0.12456703,  0.36195627],
       [ 1.09345395, -1.34251037,  0.44840796],
       ...,
       [-0.41659459, -0.56335747,  0.8155042 ],
       [-0.67894211,  0.25358396,  1.20985083],
       [-0.20458811, -1.14419738, -0.42552976]])

In [11]:
X

array([[ 1.        ,  0.9756764 ,  1.27036092, -1.14654022],
       [ 1.        , -0.71516987, -0.12456703,  0.36195627],
       [ 1.        ,  1.09345395, -1.34251037,  0.44840796],
       ...,
       [ 1.        , -0.41659459, -0.56335747,  0.8155042 ],
       [ 1.        , -0.67894211,  0.25358396,  1.20985083],
       [ 1.        , -0.20458811, -1.14419738, -0.42552976]])

In [12]:
Y

array([[ -88.04427758],
       [  28.407204  ],
       [  37.66161756],
       [  58.33846539],
       [  30.27744488],
       [ -90.87927323],
       [ -98.01644656],
       [  55.71260925],
       [ -16.55328617],
       [ -28.14084013],
       [   7.21283965],
       [  85.45232622],
       [  62.10340807],
       [-159.20198033],
       [-124.12355643],
       [-139.15264908],
       [ -45.36631066],
       [ -44.1093477 ],
       [ 170.15142241],
       [  80.31057492],
       [  -7.2244482 ],
       [ -53.96434725],
       [ -30.5497053 ],
       [-127.26115011],
       [  85.58318421],
       [  56.2288327 ],
       [  61.29295663],
       [ -37.39947886],
       [  58.07867662],
       [ -52.43260558],
       [-110.31634991],
       [ -25.80958195],
       [ -89.42322693],
       [  -6.66470593],
       [  36.65015221],
       [  33.85764939],
       [-134.70106898],
       [ -14.75489796],
       [ -49.04517714],
       [  12.22258695],
       [  38.74378738],
       [ -60.684

In [13]:
invXX = np.linalg.inv(X.transpose()@X)

beta_hat = invXX@X.transpose()@Y

y_hat = X@beta_hat

residuals = Y - y_hat

In [14]:
beta_hat

array([[ 0.53634149],
       [ 2.0310543 ],
       [ 1.0080617 ],
       [78.02800092]])

In [15]:
residuals

array([[-2.38063168e+00],
       [ 1.20625808e+00],
       [ 1.26936812e+00],
       [-1.11384256e+00],
       [ 4.27469947e-01],
       [ 1.66961617e-01],
       [ 6.08816188e-01],
       [-9.22634627e-02],
       [-1.16491488e+00],
       [-6.03343785e-01],
       [ 1.97665986e-01],
       [ 2.68161799e-01],
       [-2.65128025e+00],
       [-1.08211931e+00],
       [ 6.24983150e-04],
       [-4.64533390e-01],
       [-2.89431412e-01],
       [ 1.88499428e-01],
       [-3.76357443e-02],
       [-3.45609500e-01],
       [ 9.50132381e-01],
       [-9.14979467e-01],
       [ 1.16594015e+00],
       [ 1.29393125e+00],
       [-8.78934946e-01],
       [ 6.15923665e-01],
       [-9.94983522e-01],
       [-5.71257669e-01],
       [-2.87269457e-01],
       [-8.96707987e-01],
       [ 7.63114196e-01],
       [-1.27951556e-01],
       [ 9.67615572e-02],
       [-3.63884680e-01],
       [ 8.08733289e-01],
       [ 2.92906910e-02],
       [ 1.10987979e+00],
       [ 1.34176887e+00],
       [ 4.0

In [17]:
sigma2 = (1/T)*residuals.transpose()@residuals

sigma = np.sqrt(sigma2)

obj_func = sigma2 + 0.5*abs(beta_hat) + 0.5*(beta_hat)**2

varcov_beta_heat = (sigma2)*invXX

std_beta_hat = np.sqrt(T*np.diag(varcov_beta_heat))

R_squared = 1- (residuals.transpose()@residuals)/(T*np.)

adj_R_squared = 1- (1-R_squared)*(T-1)(T-N[1])



SyntaxError: invalid syntax (<ipython-input-17-da380376e2a5>, line 11)